"""Pairs every English string with its Polish counterpart, for review.

Run from `app/`:

    python tool/pair_translations.py

Writes `docs/TRANSLATIONS.md`. The Dart tables are the source of truth; this
only reads them. Regenerate after editing either table.
"""

import collections
import io
import re

MEMBER = re.compile(
    r"@override\s*\n\s*(?:List<\w+>|String)\s+(?:get\s+)?(\w+)([^=]*?)=>\s*(.*?);\s*\n"
    r"(?=\s*(?:@override|//|\}))",
    re.S,
)
SECTION = re.compile(r"^\s*// -+ *(.+?)\s*$", re.M)
LITERAL = re.compile(r"'((?:[^'\\]|\\.)*)'")


def parse(path):
    source = io.open(path, encoding="utf-8").read()
    members = collections.OrderedDict()
    for match in MEMBER.finditer(source):
        members[match.group(1)] = (match.group(3).strip(), match.group(2).strip())
    return members, source


def flatten(value):
    """Dart concatenation and escapes into the sentence a person reads."""
    parts = LITERAL.findall(value)
    if not parts:
        return re.sub(r"\s+", " ", value).strip()
    text = "".join(parts).replace("\\'", "'").replace("\\n", " ")
    return re.sub(r"\s+", " ", text).strip()


def main():
    english, english_source = parse("lib/core/i18n/strings_en.dart")
    polish, _ = parse("lib/core/i18n/strings_pl.dart")

    markers = [(m.start(), m.group(1)) for m in SECTION.finditer(english_source)]

    def section_of(name):
        at = english_source.find("get %s" % name)
        if at < 0:
            at = english_source.find(" %s(" % name)
        title = "general"
        for position, heading in markers:
            if position < at:
                title = heading
        return title

    rows = collections.OrderedDict()
    for name, (body, args) in english.items():
        if name not in polish:
            continue
        left, right = flatten(body), flatten(polish[name][0])
        # Identical strings are identifiers, numerals or names that never move.
        if not left or left == right:
            continue
        rows.setdefault(section_of(name), []).append((name, args, left, right))

    def cell(text):
        return text.replace("|", r"\|")

    total = 0
    with io.open("../docs/TRANSLATIONS.md", "w", encoding="utf-8") as out:
        out.write(HEADER)
        for section, items in rows.items():
            out.write("\n## %s\n\n| Key | English | Polish |\n|---|---|---|\n" % section)
            for name, args, left, right in items:
                label = name + ("()" if args.startswith("(") else "")
                out.write("| `%s` | %s | %s |\n" % (label, cell(left), cell(right)))
                total += 1
        out.write("\n---\n\n%d strings paired.\n" % total)
    print("wrote docs/TRANSLATIONS.md — %d strings" % total)


HEADER = """# Eter · every word, in both languages

Generated by `app/tool/pair_translations.py` from the two string tables, paired by
member name. **Edit the Dart tables, not this file**, then regenerate.

**How to read it.** The column that matters is the Polish one on its own, not
against the English. A translation that is accurate and still reads like a
translation is worse than a free one that sounds like something a person would
say — Eter's Polish should sound written, not localised.

Members taking a value show the sentence with its placeholder in place. Polish
inflects around those, which is why they are methods rather than strings
interpolated at the call site; see `docs/LANGUAGE.md` §3.

Excluded: anything identical in both tables. Those are identifiers, canonical
names, numerals and the wordmark — they never translate, and `LANGUAGE.md` §2
explains why translating one would break the symbolic engine.
"""


if __name__ == "__main__":
    main()
